-- Loto sonuçlarını zamanlanmış otomasyonla güvenli biçimde ekler.
-- supabase-rls.sql dosyasından SONRA Supabase SQL Editor'da bir kez çalıştırın.

alter table public.loto_draws
  add column if not exists source text not null default 'manual',
  add column if not exists source_url text,
  add column if not exists fetched_at timestamptz;

alter table public.loto_draws drop constraint if exists loto_draws_source_check;
alter table public.loto_draws
  add constraint loto_draws_source_check
  check (source in ('manual', 'milli_piyango'));

create table if not exists public.loto_sync_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'running'
    check (status in ('running', 'success', 'conflict')),
  requested_count integer not null default 0 check (requested_count >= 0),
  inserted_count integer not null default 0 check (inserted_count >= 0),
  skipped_count integer not null default 0 check (skipped_count >= 0),
  conflict_count integer not null default 0 check (conflict_count >= 0)
);

create table if not exists public.loto_sync_conflicts (
  id bigint generated by default as identity primary key,
  run_id bigint references public.loto_sync_runs(id) on delete set null,
  game text not null check (game in ('sayisal', 'super', 'sans', 'onnumara')),
  draw_date date not null,
  reason text not null,
  existing_week_no integer,
  existing_numbers smallint[],
  existing_bonus smallint,
  incoming_week_no integer not null,
  incoming_numbers smallint[] not null,
  incoming_bonus smallint,
  source_url text not null,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz
);

create unique index if not exists loto_sync_conflicts_unresolved_unique
on public.loto_sync_conflicts (game, draw_date)
where resolved_at is null;

alter table public.loto_sync_runs enable row level security;
alter table public.loto_sync_conflicts enable row level security;

revoke all privileges on table public.loto_sync_runs from public, anon, authenticated;
revoke all privileges on table public.loto_sync_conflicts from public, anon, authenticated;
revoke all privileges on sequence public.loto_sync_runs_id_seq from public, anon, authenticated;
revoke all privileges on sequence public.loto_sync_conflicts_id_seq from public, anon, authenticated;

grant select on table public.loto_sync_runs to authenticated;
grant select on table public.loto_sync_conflicts to authenticated;

drop policy if exists "Loto yoneticisi otomasyon gecmisini gorebilir" on public.loto_sync_runs;
create policy "Loto yoneticisi otomasyon gecmisini gorebilir"
on public.loto_sync_runs
for select
to authenticated
using (public.is_loto_admin());

drop policy if exists "Loto yoneticisi otomasyon cakismalarini gorebilir" on public.loto_sync_conflicts;
create policy "Loto yoneticisi otomasyon cakismalarini gorebilir"
on public.loto_sync_conflicts
for select
to authenticated
using (public.is_loto_admin());

create or replace function public.import_official_loto_results(p_rows jsonb)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  incoming record;
  existing public.loto_draws%rowtype;
  week_conflict public.loto_draws%rowtype;
  v_run_id bigint;
  v_inserted_count integer := 0;
  v_skipped_count integer := 0;
  v_conflict_count integer := 0;
  expected_count integer;
  expected_number_count integer;
  max_number integer;
  conflict_reason text;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception using
      errcode = '42501',
      message = 'Resmi sonuc aktarimi yalniz sunucu otomasyonu tarafindan calistirilabilir';
  end if;

  if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception using errcode = '22023', message = 'Aktarilacak sonuc listesi bos veya gecersiz';
  end if;

  expected_count := jsonb_array_length(p_rows);
  if expected_count > 100 then
    raise exception using errcode = '22023', message = 'Tek aktarimda en fazla 100 sonuc kabul edilir';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as row_data(
      game text,
      draw_date date,
      week_no integer,
      numbers smallint[],
      bonus smallint,
      source_url text
    )
    group by row_data.game, row_data.draw_date
    having count(*) > 1
  ) then
    raise exception using errcode = '23505', message = 'Aktarim listesinde yinelenen oyun/tarih var';
  end if;

  insert into public.loto_sync_runs (requested_count)
  values (expected_count)
  returning id into v_run_id;

  for incoming in
    select *
    from jsonb_to_recordset(p_rows) as row_data(
      game text,
      draw_date date,
      week_no integer,
      numbers smallint[],
      bonus smallint,
      source_url text
    )
    order by row_data.draw_date, row_data.game
  loop
    if incoming.game not in ('sayisal', 'super', 'sans', 'onnumara') then
      raise exception using errcode = '22023', message = 'Gecersiz loto kategorisi';
    end if;

    expected_number_count := case incoming.game when 'sans' then 5 when 'onnumara' then 22 else 6 end;
    max_number := case incoming.game when 'sayisal' then 90 when 'super' then 60 when 'sans' then 34 else 80 end;

    if incoming.draw_date is null
      or incoming.draw_date > (now() at time zone 'Europe/Istanbul')::date
      or incoming.week_no is null
      or incoming.week_no not between 1 and 9999
      or incoming.numbers is null
      or cardinality(incoming.numbers) <> expected_number_count
      or cardinality(incoming.numbers) <> (
        select count(distinct picked.number)
        from unnest(incoming.numbers) as picked(number)
      )
      or exists (
        select 1 from unnest(incoming.numbers) as picked(number)
        where picked.number < 1 or picked.number > max_number
      )
      or (incoming.game = 'sans' and (incoming.bonus is null or incoming.bonus not between 1 and 14))
      or (incoming.game <> 'sans' and incoming.bonus is not null)
      or incoming.source_url is null
      or incoming.source_url !~ '^https://www[.]millipiyangoonline[.]com/'
    then
      raise exception using
        errcode = '22023',
        message = format('%s/%s icin gecersiz resmi sonuc satiri', incoming.game, incoming.draw_date);
    end if;

    perform pg_advisory_xact_lock(hashtextextended('loto_official:' || incoming.game || ':' || incoming.draw_date::text, 0));

    select * into existing
    from public.loto_draws
    where game = incoming.game and draw_date = incoming.draw_date;

    if found then
      if existing.week_no = incoming.week_no
        and existing.numbers = incoming.numbers
        and existing.bonus is not distinct from incoming.bonus
      then
        update public.loto_draws
        set source = 'milli_piyango',
            source_url = incoming.source_url,
            fetched_at = now()
        where id = existing.id;
        v_skipped_count := v_skipped_count + 1;
        continue;
      end if;
      conflict_reason := 'Ayni tarih icin kayitli sonuc resmi kaynaktan farkli';
    else
      select * into week_conflict
      from public.loto_draws
      where game = incoming.game
        and extract(year from draw_date)::integer = extract(year from incoming.draw_date)::integer
        and week_no = incoming.week_no
        and draw_date is distinct from incoming.draw_date
      limit 1;

      if found then
        existing := week_conflict;
        conflict_reason := 'Ayni yil/cekilis numarasi baska tarihte kayitli';
      else
        insert into public.loto_draws (
          game, draw_date, week_no, numbers, bonus, source, source_url, fetched_at
        ) values (
          incoming.game,
          incoming.draw_date,
          incoming.week_no,
          incoming.numbers,
          incoming.bonus,
          'milli_piyango',
          incoming.source_url,
          now()
        );
        v_inserted_count := v_inserted_count + 1;
        continue;
      end if;
    end if;

    insert into public.loto_sync_conflicts (
      run_id, game, draw_date, reason,
      existing_week_no, existing_numbers, existing_bonus,
      incoming_week_no, incoming_numbers, incoming_bonus, source_url
    ) values (
      v_run_id, incoming.game, incoming.draw_date, conflict_reason,
      existing.week_no, existing.numbers, existing.bonus,
      incoming.week_no, incoming.numbers, incoming.bonus, incoming.source_url
    )
    on conflict (game, draw_date) where resolved_at is null
    do update set
      run_id = excluded.run_id,
      reason = excluded.reason,
      existing_week_no = excluded.existing_week_no,
      existing_numbers = excluded.existing_numbers,
      existing_bonus = excluded.existing_bonus,
      incoming_week_no = excluded.incoming_week_no,
      incoming_numbers = excluded.incoming_numbers,
      incoming_bonus = excluded.incoming_bonus,
      source_url = excluded.source_url,
      detected_at = now();

    v_conflict_count := v_conflict_count + 1;
  end loop;

  update public.loto_sync_runs
  set finished_at = now(),
      status = case when v_conflict_count > 0 then 'conflict' else 'success' end,
      inserted_count = v_inserted_count,
      skipped_count = v_skipped_count,
      conflict_count = v_conflict_count
  where id = v_run_id;

  return jsonb_build_object(
    'run_id', v_run_id,
    'requested', expected_count,
    'inserted', v_inserted_count,
    'skipped', v_skipped_count,
    'conflicts', v_conflict_count,
    'status', case when v_conflict_count > 0 then 'conflict' else 'success' end
  );
end;
$$;

revoke all on function public.import_official_loto_results(jsonb) from public, anon, authenticated;
grant execute on function public.import_official_loto_results(jsonb) to service_role;

comment on function public.import_official_loto_results(jsonb) is
'Milli Piyango sonuc sayfalarindan tarayici otomasyonuyla dogrulanan sonuclari cakisma korumali olarak ekler.';

-- Kurulum kontrolü:
-- select column_name from information_schema.columns
-- where table_schema = 'public' and table_name = 'loto_draws'
--   and column_name in ('source', 'source_url', 'fetched_at');
-- select * from public.loto_sync_runs order by id desc limit 10;
-- select * from public.loto_sync_conflicts where resolved_at is null order by detected_at desc;
