-- Supabase SQL Editor'da bir kez çalıştırın.
-- En sonda kendi Auth kullanıcı UUID'nizi loto_admins tablosuna ekleyin.

create table if not exists public.loto_draws (
  id bigint generated by default as identity primary key,
  game text not null check (game in ('sayisal', 'super', 'sans', 'onnumara')),
  draw_date date not null,
  week_no integer not null check (week_no between 1 and 9999),
  numbers smallint[] not null,
  bonus smallint,
  created_at timestamptz not null default now(),
  unique (game, draw_date)
);

create table if not exists public.loto_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.loto_draws enable row level security;
alter table public.loto_admins enable row level security;

-- Eski grantler ne olursa olsun anonim yazmayı kesin olarak kapatır.
revoke all privileges on table public.loto_draws from public, anon, authenticated;
revoke all privileges on table public.loto_admins from public, anon, authenticated;
revoke all privileges on sequence public.loto_draws_id_seq from public, anon, authenticated;

grant select on table public.loto_draws to anon, authenticated;
grant insert, update, delete on table public.loto_draws to authenticated;
grant usage, select on sequence public.loto_draws_id_seq to authenticated;

-- Tablo önceden oluşturulduysa hafta kısıtını da aynı kurala getirir.
alter table public.loto_draws drop constraint if exists loto_draws_week_no_check;
alter table public.loto_draws
  add constraint loto_draws_week_no_check check (week_no between 1 and 9999);

create or replace function public.is_loto_admin()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, public
as $$
  select exists (
    select 1
    from public.loto_admins
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_loto_admin() from public, anon;
grant execute on function public.is_loto_admin() to authenticated;

-- Aynı modern yıl/çekiliş numarasının farklı tarihlerle eşzamanlı eklenmesini
-- indeks henüz oluşturulamasa bile işlem-kapsamlı kilitle engeller.
create or replace function public.guard_loto_draw_year_week()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  draw_year integer := extract(year from new.draw_date)::integer;
begin
  if new.draw_date < date '2021-01-01' then
    return new;
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(new.game || ':' || draw_year || ':' || new.week_no, 0)
  );

  if exists (
    select 1
    from public.loto_draws as existing
    where existing.game = new.game
      and extract(year from existing.draw_date)::integer = draw_year
      and existing.week_no = new.week_no
      -- INSERT ... ON CONFLICT DO UPDATE calisirken BEFORE INSERT tetikleyicisi
      -- mevcut satirin kimligi yerine yeni bir identity degeri gorur. Ayni tarihli
      -- guvenli upsert'i engellememek icin gercek cakismayi tarihle ayiririz.
      and existing.draw_date is distinct from new.draw_date
  ) then
    raise exception using
      errcode = '23505',
      message = format(
        '%s için %s/%s çekiliş numarası başka bir tarihte zaten kayıtlı',
        new.game,
        draw_year,
        new.week_no
      );
  end if;

  return new;
end;
$$;

revoke all on function public.guard_loto_draw_year_week() from public, anon, authenticated;

drop trigger if exists loto_draws_year_week_guard on public.loto_draws;
create trigger loto_draws_year_week_guard
before insert or update of game, draw_date, week_no
on public.loto_draws
for each row execute function public.guard_loto_draw_year_week();

-- Yetkili yonetici, tek bir oyunun kanonik arsivini tek transaction icinde
-- dogrular ve degistirir. Herhangi bir satir gecersizse DELETE dahil butun
-- islem geri alinir; boylece toplu aktarim yarim kalmaz.
create or replace function public.replace_loto_archive(p_game text, p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  replaced_count integer;
  expected_count integer;
begin
  if auth.uid() is null or not public.is_loto_admin() then
    raise exception using
      errcode = '42501',
      message = 'Loto arsivini degistirmek icin yonetici yetkisi gerekli';
  end if;

  if p_game not in ('sayisal', 'super', 'sans', 'onnumara') then
    raise exception using errcode = '22023', message = 'Gecersiz loto kategorisi';
  end if;

  if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then
    raise exception using errcode = '22023', message = 'Arsiv satirlari bos veya gecersiz';
  end if;

  expected_count := jsonb_array_length(p_rows);

  -- Ayni kategori icin iki toplu degistirmenin eszamanli calismasini engeller.
  perform pg_advisory_xact_lock(hashtextextended('loto_archive_replace:' || p_game, 0));

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as incoming(
      draw_date date,
      week_no integer,
      numbers smallint[],
      bonus smallint
    )
    where incoming.draw_date is null
      or incoming.draw_date > current_date
      or incoming.week_no is null
      or incoming.week_no not between 1 and 9999
      or incoming.numbers is null
      or cardinality(incoming.numbers) <> case p_game
        when 'sans' then 5
        when 'onnumara' then 22
        else 6
      end
      or exists (
        select 1
        from unnest(incoming.numbers) as picked(number)
        where picked.number < 1
          or picked.number > case p_game
            when 'sayisal' then 90
            when 'super' then 60
            when 'sans' then 34
            else 80
          end
      )
      or cardinality(incoming.numbers) <> (
        select count(distinct picked.number)
        from unnest(incoming.numbers) as picked(number)
      )
      or (p_game = 'sans' and (incoming.bonus is null or incoming.bonus not between 1 and 14))
      or (p_game <> 'sans' and incoming.bonus is not null)
  ) then
    raise exception using errcode = '22023', message = 'Arsivde gecersiz cekilis satiri var';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as incoming(
      draw_date date,
      week_no integer,
      numbers smallint[],
      bonus smallint
    )
    group by incoming.draw_date
    having count(*) > 1
  ) then
    raise exception using errcode = '23505', message = 'Arsivde yinelenen cekilis tarihi var';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(p_rows) as incoming(
      draw_date date,
      week_no integer,
      numbers smallint[],
      bonus smallint
    )
    where incoming.draw_date >= date '2021-01-01'
    group by extract(year from incoming.draw_date)::integer, incoming.week_no
    having count(*) > 1
  ) then
    raise exception using errcode = '23505', message = 'Arsivde yinelenen yil/cekilis numarasi var';
  end if;

  delete from public.loto_draws where game = p_game;

  insert into public.loto_draws (game, draw_date, week_no, numbers, bonus)
  select
    p_game,
    incoming.draw_date,
    incoming.week_no,
    incoming.numbers,
    incoming.bonus
  from jsonb_to_recordset(p_rows) as incoming(
    draw_date date,
    week_no integer,
    numbers smallint[],
    bonus smallint
  )
  order by incoming.draw_date;

  get diagnostics replaced_count = row_count;
  if replaced_count <> expected_count then
    raise exception using errcode = 'P0001', message = 'Arsiv satir sayisi dogrulanamadi';
  end if;

  -- Son bozuk kategori de temizlendiginde kalici benzersiz indeks otomatik
  -- olarak olusturulur; kullanicinin migration'i tekrar calistirmasi gerekmez.
  if not exists (
    select 1
    from public.loto_draws
    where draw_date >= date '2021-01-01'
    group by game, extract(year from draw_date)::integer, week_no
    having count(*) > 1
  ) then
    execute 'create unique index if not exists loto_draws_game_year_week_unique_modern
      on public.loto_draws (game, (extract(year from draw_date)::integer), week_no)
      where draw_date >= date ''2021-01-01''';
  end if;

  return replaced_count;
end;
$$;

revoke all on function public.replace_loto_archive(text, jsonb) from public, anon;
grant execute on function public.replace_loto_archive(text, jsonb) to authenticated;

-- Eski tabloda çakışma yoksa veritabanı seviyesinde kalıcı benzersiz indeks
-- oluşturur. Çakışma varsa güvenlik kuralları uygulanmaya devam eder ve
-- aşağıdaki tanı sorgusuyla düzeltilecek kayıtlar SQL Editor uyarısında belirtilir.
do $$
begin
  if exists (
    select 1
    from public.loto_draws
    where draw_date >= date '2021-01-01'
    group by game, extract(year from draw_date)::integer, week_no
    having count(*) > 1
  ) then
    raise warning 'Modern arşivde yinelenen yıl/çekiliş numarası var; loto_draws_game_year_week_unique_modern indeksi oluşturulmadı. Dosyanın sonundaki tanı sorgusunu çalıştırın.';
  else
    execute 'create unique index if not exists loto_draws_game_year_week_unique_modern
      on public.loto_draws (game, (extract(year from draw_date)::integer), week_no)
      where draw_date >= date ''2021-01-01''';
  end if;
end;
$$;

-- Bilinmeyen adlarla kalmış eski permissive yazma politikalarını da temizler.
do $$
declare
  old_policy record;
begin
  for old_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'loto_draws'
      and cmd in ('ALL', 'INSERT', 'UPDATE', 'DELETE')
  loop
    execute format('drop policy if exists %I on public.loto_draws', old_policy.policyname);
  end loop;
end;
$$;

drop policy if exists "Loto arsivi herkese acik" on public.loto_draws;
create policy "Loto arsivi herkese acik"
on public.loto_draws
for select
to anon, authenticated
using (true);

create policy "Loto yoneticisi ekleyebilir"
on public.loto_draws
for insert
to authenticated
with check (public.is_loto_admin());

create policy "Loto yoneticisi guncelleyebilir"
on public.loto_draws
for update
to authenticated
using (public.is_loto_admin())
with check (public.is_loto_admin());

create policy "Loto yoneticisi silebilir"
on public.loto_draws
for delete
to authenticated
using (public.is_loto_admin());

-- Kendi Supabase Auth kullanıcı UUID'nizi yazarak yöneticiyi tanımlayın:
-- insert into public.loto_admins (user_id)
-- values ('00000000-0000-0000-0000-000000000000')
-- on conflict (user_id) do nothing;

-- İndeks uyarısı aldıysanız önce bu salt-okunur sorguyla çakışmaları bulun:
-- select game, extract(year from draw_date)::integer as draw_year, week_no,
--        array_agg(draw_date order by draw_date) as dates
-- from public.loto_draws
-- where draw_date >= date '2021-01-01'
-- group by game, extract(year from draw_date)::integer, week_no
-- having count(*) > 1;
